export const sampleColumns: any = [
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.578Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.578Z',
    modifiedOn: '2021-09-24T10:21:32.101Z',
    createdBy: null,
    modifiedBy: 'b7a67fb9-5468-33cf-9c98-ced007196769',
    id: '72464e1d-835d-f78e-e31c-759238c614a7',
    name: 'aaa cc',
    description: null,
    level: 0,
    metaData: {
      availableStatus: [
        {
          text: 'Active',
          color: '#ff0000',
          value: 'Active',
          iconClass: 'status',
          displayValue: 'Active',
        },
        {
          text: 'Completed',
          color: '#ffcc00',
          value: 'Completed',
          iconClass: 'status',
          displayValue: 'Completed',
        },
        {
          text: 'To be HO to Dept',
          color: '#50c878',
          value: 'To be HO to Dept',
          iconClass: 'status',
          displayValue: 'To Be Ho To Dept',
        },
        {
          text: 'To be confirmed',
          color: '#c6e1e8',
          value: 'To be confirmed',
          iconClass: 'status',
          displayValue: 'To Be Confirmed',
        },
      ],
    },
    sequenceNumber: 0,
    columnType: 'status',
    format: {
      bold: {
        value: true,
        modified: '2021-09-24T09:29:05.111Z',
      },
      italic: {
        value: true,
        modified: '2021-09-24T09:29:06.272Z',
      },
      underlined: {
        value: true,
        modified: '2021-09-24T09:29:06.903Z',
      },
    },
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-24T09:31:28.766Z',
    deletedBy: null,
    createdOn: '2021-09-24T09:31:28.766Z',
    modifiedOn: '2021-09-24T10:19:05.454Z',
    createdBy: '855a04ac-3f28-ebd0-9ea7-4816b0818f2e',
    modifiedBy: '855a04ac-3f28-ebd0-9ea7-4816b0818f2e',
    id: 'c9b62c89-7191-3155-701d-0b448c0226e4',
    name: 'aaaManagement Input (copy)',
    description: null,
    level: 0,
    metaData: {
      availableStatus: [
        {
          text: 'Active',
          color: '#ff0000',
          value: 'Active',
          iconClass: 'status',
          displayValue: 'Active',
        },
        {
          text: 'Completed',
          color: '#ffcc00',
          value: 'Completed',
          iconClass: 'status',
          displayValue: 'Completed',
        },
        {
          text: 'To be HO to Dept',
          color: '#50c878',
          value: 'To be HO to Dept',
          iconClass: 'status',
          displayValue: 'To Be Ho To Dept',
        },
        {
          text: 'To be confirmed',
          color: '#c6e1e8',
          value: 'To be confirmed',
          iconClass: 'status',
          displayValue: 'To Be Confirmed',
        },
      ],
    },
    sequenceNumber: 0.5,
    columnType: 'status',
    format: {
      bold: {
        value: true,
        modified: '2021-09-24T09:29:05.111Z',
      },
      italic: {
        value: true,
        modified: '2021-09-24T09:29:06.272Z',
      },
      underlined: {
        value: true,
        modified: '2021-09-24T09:29:06.903Z',
      },
    },
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.578Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.578Z',
    modifiedOn: '2021-09-24T09:29:03.518Z',
    createdBy: null,
    modifiedBy: '855a04ac-3f28-ebd0-9ea7-4816b0818f2e',
    id: 'e743bf0e-3097-1ebd-86c1-5f90b86c5352',
    name: 'aaa',
    description: null,
    level: 0,
    metaData: {
      message: 'Text Column Value Required',
      required: false,
    },
    sequenceNumber: 1,
    columnType: 'text',
    format: {
      bold: {
        value: true,
        modified: '2021-09-24T09:29:01.554Z',
      },
      italic: {
        value: true,
        modified: '2021-09-24T09:29:02.110Z',
      },
    },
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-24T09:31:11.243Z',
    deletedBy: null,
    createdOn: '2021-09-24T09:31:11.243Z',
    modifiedOn: '2021-09-24T09:31:11.243Z',
    createdBy: '855a04ac-3f28-ebd0-9ea7-4816b0818f2e',
    modifiedBy: '855a04ac-3f28-ebd0-9ea7-4816b0818f2e',
    id: '51cf85e6-1a1d-ffae-e6cd-0e1c88e82267',
    name: 'aaa (copy)',
    description: null,
    level: 0,
    metaData: {
      message: 'Text Column Value Required',
      required: false,
    },
    sequenceNumber: 2,
    columnType: 'text',
    format: {
      bold: {
        value: true,
        modified: '2021-09-24T09:29:01.554Z',
      },
      italic: {
        value: true,
        modified: '2021-09-24T09:29:02.110Z',
      },
    },
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.578Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.578Z',
    modifiedOn: '2021-09-24T09:29:11.523Z',
    createdBy: null,
    modifiedBy: '855a04ac-3f28-ebd0-9ea7-4816b0818f2e',
    id: '8a1447e9-1736-fc63-c9eb-dc1d5efd91d1',
    name: 'Sponsor Name11',
    description: null,
    level: 0,
    metaData: {
      options: [
        {
          text: 'Kazuaki Ban',
          value: 'Kazuaki Ban',
          displayValue: 'Kazuaki Ban',
        },
        {
          text: 'Sharad Sriwastawa',
          value: 'Sharad Sriwastawa',
          displayValue: 'Sharad Sriwastawa',
        },
        {
          text: '"wong Perry, Elaine"',
          value: '"Wong Perry, Elaine"',
          displayValue: '"wong Perry, Elaine"',
        },
        {
          text: 'Mina Nicola',
          value: 'Mina Nicola',
          displayValue: 'Mina Nicola',
        },
        {
          text: 'Hiroshi Takeshita',
          value: 'Hiroshi Takeshita',
          displayValue: 'Hiroshi Takeshita',
        },
        {
          text: 'Shailesh Gupta',
          value: 'Shailesh Gupta',
          displayValue: 'Shailesh Gupta',
        },
        {
          text: 'Vikas Kukreja',
          value: 'Vikas Kukreja',
          displayValue: 'Vikas Kukreja',
        },
        {
          text: 'Mahesh Kasar',
          value: 'Mahesh Kasar',
          displayValue: 'Mahesh Kasar',
        },
        {
          text: 'Puneet Handa',
          value: 'Puneet Handa',
          displayValue: 'Puneet Handa',
        },
        {
          text: 'Ryoji Osaka',
          value: 'Ryoji Osaka',
          displayValue: 'Ryoji Osaka',
        },
        {
          text: 'Eric Olsen',
          value: 'Eric Olsen',
          displayValue: 'Eric Olsen',
        },
        {
          text: 'Sivabalan Arumugam',
          value: 'Sivabalan Arumugam',
          displayValue: 'Sivabalan Arumugam',
        },
        {
          text: 'Utkarsh Sinha',
          value: 'Utkarsh Sinha',
          displayValue: 'Utkarsh Sinha',
        },
        {
          text: 'Hiren.joshi@rakuten.com',
          value: 'hiren.joshi@rakuten.com',
          displayValue: 'Hiren.joshi@rakuten.com',
        },
        {
          text: 'Koichiro Furueda',
          value: 'Koichiro Furueda',
          displayValue: 'Koichiro Furueda',
        },
        {
          text: 'Medithe Madhukiran',
          value: 'Medithe Madhukiran',
          displayValue: 'Medithe Madhukiran',
        },
        {
          text: 'Jenis Modi',
          value: 'Jenis Modi',
          displayValue: 'Jenis Modi',
        },
        {
          text: 'Pradheepkumar Singaravelu',
          value: 'Pradheepkumar Singaravelu',
          displayValue: 'Pradheepkumar Singaravelu',
        },
        {
          text: 'Satyam Prajapati',
          value: 'Satyam Prajapati',
          displayValue: 'Satyam Prajapati',
        },
        {
          text: 'Tadashi Tsukamoto',
          value: 'Tadashi Tsukamoto',
          displayValue: 'Tadashi Tsukamoto',
        },
        {
          text: 'Francis Jebamani',
          value: 'Francis Jebamani',
          displayValue: 'Francis Jebamani',
        },
        {
          text: 'Nobuyuki Uchida',
          value: 'Nobuyuki Uchida',
          displayValue: 'Nobuyuki Uchida',
        },
        {
          text: 'Brijesh Yadav',
          value: 'Brijesh Yadav',
          displayValue: 'Brijesh Yadav',
        },
        {
          text: 'Shailesh',
          value: 'Shailesh',
          displayValue: 'Shailesh',
        },
        {
          text: 'Anshul Bhatt',
          value: 'Anshul Bhatt',
          displayValue: 'Anshul Bhatt',
        },
        {
          text: 'Sushil Rawat',
          value: 'Sushil Rawat',
          displayValue: 'Sushil Rawat',
        },
        {
          text: 'Ryo Watanabe',
          value: 'Ryo Watanabe',
          displayValue: 'Ryo Watanabe',
        },
        {
          text: 'Mitsuhiro Kuchitsu',
          value: 'Mitsuhiro Kuchitsu',
          displayValue: 'Mitsuhiro Kuchitsu',
        },
        {
          text: 'Yuji Nishii (citd)',
          value: 'Yuji Nishii (CITD)',
          displayValue: 'Yuji Nishii (citd)',
        },
        {
          text: 'Michiel Koens',
          value: 'Michiel Koens',
          displayValue: 'Michiel Koens',
        },
        {
          text: 'Anil.pawar@rakuten.com',
          value: 'anil.pawar@rakuten.com',
          displayValue: 'Anil.pawar@rakuten.com',
        },
        {
          text: 'Hazari Singh',
          value: 'Hazari Singh',
          displayValue: 'Hazari Singh',
        },
        {
          text: 'Masato Abe',
          value: 'Masato Abe',
          displayValue: 'Masato Abe',
        },
        {
          text: 'Shuichi Yoshino',
          value: 'Shuichi Yoshino',
          displayValue: 'Shuichi Yoshino',
        },
      ],
    },
    sequenceNumber: 3,
    columnType: 'dropdown',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.578Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.578Z',
    modifiedOn: '2021-09-07T12:35:42.615Z',
    createdBy: null,
    modifiedBy: 'f7817453-27b3-d45e-e941-0c5f4c2dc42b',
    id: '273dd36b-29f1-9d69-83cd-354702984018',
    name: 'Start Date',
    description: null,
    level: 0,
    metaData: {
      width: '502',
      format: 'M/d/yyyy',
      dayOfWeek: false,
      currentYear: false,
    },
    sequenceNumber: 4,
    columnType: 'date',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.578Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.578Z',
    modifiedOn: '2021-09-05T11:19:44.578Z',
    createdBy: null,
    modifiedBy: null,
    id: 'b2816d8d-61b9-f6d3-5767-2598ea7efd25',
    name: 'Target End Date',
    description: null,
    level: 0,
    metaData: {},
    sequenceNumber: 5,
    columnType: 'text',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.578Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.578Z',
    modifiedOn: '2021-09-05T11:19:44.578Z',
    createdBy: null,
    modifiedBy: null,
    id: '7c790337-b129-d4ab-6da6-44b0ec27f34f',
    name: 'PMD Section',
    description: null,
    level: 0,
    metaData: {
      options: [
        {
          value: 'Transformational',
          displayValue: 'Transformational',
        },
        {
          value: 'Cloud',
          displayValue: 'Cloud',
        },
        {
          value: 'Connectivity',
          displayValue: 'Connectivity',
        },
        {
          value: 'Automation',
          displayValue: 'Automation',
        },
        {
          value: 'Product',
          displayValue: 'Product',
        },
        {
          value: 'Security',
          displayValue: 'Security',
        },
        {
          value: 'AI & QA',
          displayValue: 'Ai & Qa',
        },
        {
          value: 'Special Projects',
          displayValue: 'Special Projects',
        },
      ],
    },
    sequenceNumber: 6,
    columnType: 'dropdown',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.578Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.578Z',
    modifiedOn: '2021-09-05T11:19:44.578Z',
    createdBy: null,
    modifiedBy: null,
    id: '34a8c168-3baa-a0e4-6671-37ce877f5506',
    name: 'Project Criticality',
    description: null,
    level: 0,
    metaData: {
      options: [
        {
          value: 'Major',
          displayValue: 'Major',
        },
        {
          value: 'Critical',
          displayValue: 'Critical',
        },
        {
          value: 'Medium',
          displayValue: 'Medium',
        },
        {
          value: 'Minor',
          displayValue: 'Minor',
        },
      ],
    },
    sequenceNumber: 7,
    columnType: 'dropdown',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.578Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.578Z',
    modifiedOn: '2021-09-05T11:19:44.578Z',
    createdBy: null,
    modifiedBy: null,
    id: 'aa83aec7-6aac-dd96-57bf-f67d0e2d9104',
    name: 'Primary Project Manager',
    description: null,
    level: 0,
    metaData: {
      availableStatus: [
        {
          color: '#ff0000',
          value: 'Ahmed Mostafa',
          displayValue: 'Ahmed Mostafa',
        },
        {
          color: '#ffcc00',
          value: 'airi.igarashi@rakuten.com',
          displayValue: 'Airi.igarashi@rakuten.com',
        },
        {
          color: '#50c878',
          value: 'Akito Fushimi',
          displayValue: 'Akito Fushimi',
        },
        {
          color: '#c6e1e8',
          value: 'Amandeep Rana',
          displayValue: 'Amandeep Rana',
        },
        {
          color: '#d1d1e0',
          value: 'Cedric Langlois',
          displayValue: 'Cedric Langlois',
        },
        {
          color: '#a48a9e',
          value: 'Chetan Pandey',
          displayValue: 'Chetan Pandey',
        },
        {
          color: '#ea9e70',
          value: 'david.lunt@rakuten.com',
          displayValue: 'David.lunt@rakuten.com',
        },
        {
          color: '#ce7d78',
          value: 'Duane Hohmura',
          displayValue: 'Duane Hohmura',
        },
        {
          color: '#63b598',
          value: 'Gagandeep singh',
          displayValue: 'Gagandeep Singh',
        },
        {
          color: '#64820f',
          value: 'Isooda Ajdari',
          displayValue: 'Isooda Ajdari',
        },
        {
          color: '#6b2e5f',
          value: 'jothibhaskar.m@rakuten.com',
          displayValue: 'Jothibhaskar.m@rakuten.com',
        },
        {
          color: '#1bb699',
          value: 'Jyoti',
          displayValue: 'Jyoti',
        },
        {
          color: '#fa06ec',
          value: 'Kaori Uchida',
          displayValue: 'Kaori Uchida',
        },
        {
          color: '#b2be57',
          value: 'Kouhei Taguchi',
          displayValue: 'Kouhei Taguchi',
        },
        {
          color: '#e33e52',
          value: 'Kshitish Behera',
          displayValue: 'Kshitish Behera',
        },
        {
          color: '#d6dd92',
          value: 'Kuan-Yu Chen',
          displayValue: 'Kuan-yu Chen',
        },
        {
          color: '#c79ed2',
          value: 'Malti Negi',
          displayValue: 'Malti Negi',
        },
        {
          color: '#521250',
          value: 'Manoranjan Singh',
          displayValue: 'Manoranjan Singh',
        },
        {
          color: '#79352c',
          value: 'Praksh Pathak',
          displayValue: 'Praksh Pathak',
        },
        {
          color: '#ea24a3',
          value: 'Pranita Dhoka',
          displayValue: 'Pranita Dhoka',
        },
        {
          color: '#983f7a',
          value: 'prashant.b.sonar@rakuten.com',
          displayValue: 'Prashant.b.sonar@rakuten.com',
        },
        {
          color: '#f50422',
          value: 'Rahul Goyal',
          displayValue: 'Rahul Goyal',
        },
        {
          color: '#986b53',
          value: 'Ritika Kukreja',
          displayValue: 'Ritika Kukreja',
        },
        {
          color: '#3b8c2a',
          value: 'Roy Davidson',
          displayValue: 'Roy Davidson',
        },
        {
          color: '#0023b8',
          value: 'Ruiko Asano',
          displayValue: 'Ruiko Asano',
        },
        {
          color: '#7fb411',
          value: 'Saki Kiko',
          displayValue: 'Saki Kiko',
        },
        {
          color: '#d36647',
          value: 'Saori Nishiura',
          displayValue: 'Saori Nishiura',
        },
        {
          color: '#89d534',
          value: 'shaveta.vatrana@rakuten.com',
          displayValue: 'Shaveta.vatrana@rakuten.com',
        },
        {
          color: '#21538e',
          value: 'shiho.a.hoshino@rakuten.com',
          displayValue: 'Shiho.a.hoshino@rakuten.com',
        },
        {
          color: '#807fb',
          value: 'Som Singh Negi',
          displayValue: 'Som Singh Negi',
        },
        {
          color: '#5bb32d',
          value: 'Sumit Agarwal',
          displayValue: 'Sumit Agarwal',
        },
        {
          color: '#51aed9',
          value: 'Tej Rudani',
          displayValue: 'Tej Rudani',
        },
        {
          color: '#fb21a3',
          value: 'ts-jyoti.rani@rakuten.com',
          displayValue: 'Ts-jyoti.rani@rakuten.com',
        },
        {
          color: '#41d158',
          value: 'Vishnukumar Mahalingam',
          displayValue: 'Vishnukumar Mahalingam',
        },
        {
          color: '#c9a941',
          value: 'Xinnan Yao',
          displayValue: 'Xinnan Yao',
        },
        {
          color: '#c3c89d',
          value: 'Yasuo Saito',
          displayValue: 'Yasuo Saito',
        },
        {
          color: '#b2b4f0',
          value: 'Yuta Hamasaki',
          displayValue: 'Yuta Hamasaki',
        },
      ],
    },
    sequenceNumber: 9,
    columnType: 'status',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.578Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.578Z',
    modifiedOn: '2021-09-05T11:19:44.578Z',
    createdBy: null,
    modifiedBy: null,
    id: '43eb3f04-842a-af84-795d-5062e44ca8ba',
    name: 'Primary PM Utilization (h)',
    description: null,
    level: 0,
    metaData: {},
    sequenceNumber: 10,
    columnType: 'number',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.578Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.578Z',
    modifiedOn: '2021-09-05T11:19:44.578Z',
    createdBy: null,
    modifiedBy: null,
    id: '575cd92b-8b80-c0ec-540d-422d58757d34',
    name: 'Secondary Project Manager',
    description: null,
    level: 0,
    metaData: {},
    sequenceNumber: 11,
    columnType: 'text',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.578Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.578Z',
    modifiedOn: '2021-09-05T11:19:44.578Z',
    createdBy: null,
    modifiedBy: null,
    id: '5b59c340-ffe4-4f06-d010-834a27063f93',
    name: 'Secondary PM Utilization (h)',
    description: null,
    level: 0,
    metaData: {},
    sequenceNumber: 12,
    columnType: 'number',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.578Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.578Z',
    modifiedOn: '2021-09-05T11:19:44.578Z',
    createdBy: null,
    modifiedBy: null,
    id: '39362a4a-229d-9fab-7891-b4ec3d40b830',
    name: '% Project Completion',
    description: null,
    level: 0,
    metaData: {},
    sequenceNumber: 13,
    columnType: 'text',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.578Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.578Z',
    modifiedOn: '2021-09-16T11:18:23.469Z',
    createdBy: null,
    modifiedBy: '855a04ac-3f28-ebd0-9ea7-4816b0818f2e',
    id: '67f70004-0b7d-78ca-0a95-4b4961065f66',
    name: 'Project Status',
    description: null,
    level: 0,
    metaData: {
      width: '432',
      availableStatus: [
        {
          text: 'In-Progress',
          color: '#ff0000',
          value: 'In-Progress',
          iconClass: 'status',
          displayValue: 'In-progress',
        },
        {
          text: 'Completed',
          color: '#ffcc00',
          value: 'Completed',
          iconClass: 'status',
          displayValue: 'Completed',
        },
        {
          text: 'Blocked',
          color: '#50c878',
          value: 'Blocked',
          iconClass: 'status',
          displayValue: 'Blocked',
        },
        {
          text: 'On hold',
          color: '#c6e1e8',
          value: 'On hold',
          iconClass: 'status',
          displayValue: 'On Hold',
        },
        {
          text: 'on hold',
          color: '#d1d1e0',
          value: 'on hold',
          iconClass: 'status',
          displayValue: 'On Hold',
        },
        {
          text: 'On-Hold',
          color: '#a48a9e',
          value: 'On-Hold',
          iconClass: 'status',
          displayValue: 'On-hold',
        },
      ],
    },
    sequenceNumber: 14,
    columnType: 'status',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.578Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.578Z',
    modifiedOn: '2021-09-05T11:19:44.578Z',
    createdBy: null,
    modifiedBy: null,
    id: '59764f9d-2465-3417-6486-fab7d518e298',
    name: 'RAG Status',
    description: null,
    level: 0,
    metaData: {
      availableStatus: [
        {
          color: '#ff0000',
          value: 'Green',
          displayValue: 'Green',
        },
        {
          color: '#ffcc00',
          value: 'Yellow',
          displayValue: 'Yellow',
        },
        {
          color: '#50c878',
          value: 'Blue',
          displayValue: 'Blue',
        },
        {
          color: '#c6e1e8',
          value: 'Red',
          displayValue: 'Red',
        },
      ],
    },
    sequenceNumber: 15,
    columnType: 'status',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.578Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.578Z',
    modifiedOn: '2021-09-05T11:19:44.578Z',
    createdBy: null,
    modifiedBy: null,
    id: 'efeb4ed6-d36c-87cc-9749-70127027b4c4',
    name: 'RPMM Phase',
    description: null,
    level: 0,
    metaData: {
      options: [
        {
          value: 'Initiation',
          displayValue: 'Initiation',
        },
        {
          value: 'Execution',
          displayValue: 'Execution',
        },
        {
          value: 'Planning',
          displayValue: 'Planning',
        },
        {
          value: 'Closure',
          displayValue: 'Closure',
        },
      ],
    },
    sequenceNumber: 16,
    columnType: 'dropdown',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.578Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.578Z',
    modifiedOn: '2021-09-05T11:19:44.578Z',
    createdBy: null,
    modifiedBy: null,
    id: '750015b5-42b2-3748-6327-2366fb25f467',
    name: 'Project Criticality Definition',
    description: null,
    level: 0,
    metaData: {
      availableStatus: [
        {
          color: '#ff0000',
          value: 'MIC Obligation',
          displayValue: 'Mic Obligation',
        },
        {
          color: '#ffcc00',
          value: 'Tareq priority',
          displayValue: 'Tareq Priority',
        },
        {
          color: '#50c878',
          value: 'NB-IoT',
          displayValue: 'Nb-iot',
        },
        {
          color: '#c6e1e8',
          value: 'In-house device mgmt platform to replace IMPACT.',
          displayValue: 'In-house Device Mgmt Platform To Replace Impact.',
        },
        {
          color: '#d1d1e0',
          value: 'RM Training needs',
          displayValue: 'Rm Training Needs',
        },
        {
          color: '#a48a9e',
          value: 'Critical',
          displayValue: 'Critical',
        },
        {
          color: '#ea9e70',
          value: 'Strategic Business  Importance',
          displayValue: 'Strategic Business  Importance',
        },
        {
          color: '#ce7d78',
          value:
            'Deployment of Test Agents in Core Network for Performance Management.',
          displayValue:
            'Deployment Of Test Agents In Core Network For Performance Management.',
        },
        {
          color: '#63b598',
          value: 'Important and long outstand issue for Management',
          displayValue: 'Important And Long Outstand Issue For Management',
        },
        {
          color: '#64820f',
          value: 'Comes from Upper Management',
          displayValue: 'Comes From Upper Management',
        },
        {
          color: '#6b2e5f',
          value: 'MiC Obligation',
          displayValue: 'Mic Obligation',
        },
        {
          color: '#1bb699',
          value: 'On hold',
          displayValue: 'On Hold',
        },
        {
          color: '#fa06ec',
          value: 'very important for SPD/CISO',
          displayValue: 'Very Important For Spd/ciso',
        },
        {
          color: '#b2be57',
          value:
            'Cloud team to clear Sec Integrations required to unblock app onboarding.',
          displayValue:
            'Cloud Team To Clear Sec Integrations Required To Unblock App Onboarding.',
        },
        {
          color: '#e33e52',
          value: 'not immediately required by SPD, not currently resourced',
          displayValue:
            'Not Immediately Required By Spd, Not Currently Resourced',
        },
        {
          color: '#d6dd92',
          value:
            'migrate Rakuten Cloud to RCP/OneCloud as Virtual Machines and not as container which is current technology',
          displayValue:
            'Migrate Rakuten Cloud To Rcp/onecloud As Virtual Machines And Not As Container Which Is Current Technology',
        },
        {
          color: '#c79ed2',
          value:
            'RMI readiness for 11M subscriber. No direction to move forward.',
          displayValue:
            'Rmi Readiness For 11m Subscriber. No Direction To Move Forward.',
        },
        {
          color: '#521250',
          value: 'Procurement, Desgin/planning for POC at TX, USA by June-July',
          displayValue:
            'Procurement, Desgin/planning For Poc At Tx, Usa By June-july',
        },
        {
          color: '#79352c',
          value: '3 devices are priority - hand 5g, new 5g device, new CPE.',
          displayValue:
            '3 Devices Are Priority - Hand 5g, New 5g Device, New Cpe.',
        },
        {
          color: '#ea24a3',
          value:
            'New BI tool to use and bundled for whole RCP and RMI products.',
          displayValue:
            'New Bi Tool To Use And Bundled For Whole Rcp And Rmi Products.',
        },
        {
          color: '#983f7a',
          value:
            'It is Automation for lots of procedure to be handled by SXC or other dept to fix critical usecases',
          displayValue:
            'It Is Automation For Lots Of Procedure To Be Handled By Sxc Or Other Dept To Fix Critical Usecases',
        },
        {
          color: '#f50422',
          value:
            'As per regulations team, it is pre-requisite for Telecom operators to have SNI redunancy',
          displayValue:
            'As Per Regulations Team, It Is Pre-requisite For Telecom Operators To Have Sni Redunancy',
        },
        {
          color: '#986b53',
          value: 'Needed for Sec cluster & Source Code Managment',
          displayValue: 'Needed For Sec Cluster & Source Code Managment',
        },
        {
          color: '#3b8c2a',
          value: 'Stong requirement from Mangement/Business',
          displayValue: 'Stong Requirement From Mangement/business',
        },
        {
          color: '#0023b8',
          value: 'needed for CVIM replacement & new DCs',
          displayValue: 'Needed For Cvim Replacement & New Dcs',
        },
        {
          color: '#7fb411',
          value: 'Component of bilateral roaming.',
          displayValue: 'Component Of Bilateral Roaming.',
        },
        {
          color: '#d36647',
          value:
            'Migration of Existing foresight and siteforge Modules to RCP-ROSS Platform by Sept-Oct',
          displayValue:
            'Migration Of Existing Foresight And Siteforge Modules To Rcp-ross Platform By Sept-oct',
        },
        {
          color: '#89d534',
          value:
            'This is used by CS agents & it involves 2 staging releases + 1 production release per sprint/per month. Upper management is keeping a tab on this project on regular basis. Currently rakuten mobile has customer base of ~3.8 M',
          displayValue:
            'This Is Used By Cs Agents & It Involves 2 Staging Releases + 1 Production Release Per Sprint/per Month. Upper Management Is Keeping A Tab On This Project On Regular Basis. Currently Rakuten Mobile Has Customer Base Of ~3.8 M',
        },
        {
          color: '#21538e',
          value: 'RMI OBF APP onboarding',
          displayValue: 'Rmi Obf App Onboarding',
        },
        {
          color: '#807fb',
          value: 'Crash dump and Log consolidation for 4G/5G devices and infra',
          displayValue:
            'Crash Dump And Log Consolidation For 4g/5g Devices And Infra',
        },
        {
          color: '#5bb32d',
          value: 'Omnicare uses datalake to fetch customer details',
          displayValue: 'Omnicare Uses Datalake To Fetch Customer Details',
        },
        {
          color: '#51aed9',
          value: 'iPhone support requirement',
          displayValue: 'Iphone Support Requirement',
        },
        {
          color: '#fb21a3',
          value: 'Hard deadline for DC migration',
          displayValue: 'Hard Deadline For Dc Migration',
        },
        {
          color: '#41d158',
          value:
            'Security assurance is going to work on pre-arb and arb for Axonius project. Axonius is a cybersecurity asset management tool providing discovery information visibly in RM environment.',
          displayValue:
            'Security Assurance Is Going To Work On Pre-arb And Arb For Axonius Project. Axonius Is A Cybersecurity Asset Management Tool Providing Discovery Information Visibly In Rm Environment.',
        },
        {
          color: '#c9a941',
          value:
            'To deploy an Inbound and Outbound Distributed Denial of Service (DDoS) solution for Rakuten Mobile 5G rollout. Allot DDoS solution will be used.',
          displayValue:
            'To Deploy An Inbound And Outbound Distributed Denial Of Service (ddos) Solution For Rakuten Mobile 5g Rollout. Allot Ddos Solution Will Be Used.',
        },
        {
          color: '#c3c89d',
          value: 'Minimize onsite support',
          displayValue: 'Minimize Onsite Support',
        },
        {
          color: '#b2b4f0',
          value: 'MIC commerical product obligation.',
          displayValue: 'Mic Commerical Product Obligation.',
        },
        {
          color: '#8fb413',
          value: 'International Biz Dev requirement.',
          displayValue: 'International Biz Dev Requirement.',
        },
        {
          color: '#0971f0',
          value: 'Public announcement from Tareq',
          displayValue: 'Public Announcement From Tareq',
        },
        {
          color: '#6749e8',
          value:
            'Establish service interaction between Automation and Security teams',
          displayValue:
            'Establish Service Interaction Between Automation And Security Teams',
        },
      ],
    },
    sequenceNumber: 17,
    columnType: 'status',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.578Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.578Z',
    modifiedOn: '2021-09-05T11:19:44.578Z',
    createdBy: null,
    modifiedBy: null,
    id: '9d6eb876-a18e-bbaa-8251-23eee63f25af',
    name: 'RCP Application Onboarding',
    description: null,
    level: 0,
    metaData: {
      availableStatus: [
        {
          color: '#ff0000',
          value: 'not started yet',
          displayValue: 'Not Started Yet',
        },
        {
          color: '#ffcc00',
          value: 'staging',
          displayValue: 'Staging',
        },
        {
          color: '#50c878',
          value: 'N/A',
          displayValue: 'N/a',
        },
        {
          color: '#c6e1e8',
          value: 'Pre-ARB',
          displayValue: 'Pre-arb',
        },
        {
          color: '#d1d1e0',
          value: 'Production',
          displayValue: 'Production',
        },
        {
          color: '#a48a9e',
          value: 'NA',
          displayValue: 'Na',
        },
        {
          color: '#ea9e70',
          value: 'N//A',
          displayValue: 'N//a',
        },
        {
          color: '#ce7d78',
          value: 'Staging',
          displayValue: 'Staging',
        },
        {
          color: '#63b598',
          value: 'Sandbox',
          displayValue: 'Sandbox',
        },
      ],
    },
    sequenceNumber: 18,
    columnType: 'status',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.578Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.578Z',
    modifiedOn: '2021-09-05T11:19:44.578Z',
    createdBy: null,
    modifiedBy: null,
    id: '09328347-7d1d-9670-adc1-5aa41d1e1acf',
    name: 'Reason for RAG',
    description: null,
    level: 0,
    metaData: {},
    sequenceNumber: 19,
    columnType: 'text',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.578Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.578Z',
    modifiedOn: '2021-09-05T11:19:44.578Z',
    createdBy: null,
    modifiedBy: null,
    id: '4a193244-d59a-6eab-b312-ff7c554f6c5c',
    name: 'Comments',
    description: null,
    level: 0,
    metaData: {
      availableStatus: [
        {
          color: '#ff0000',
          value: 'PO not issued to Mobileum',
          displayValue: 'Po Not Issued To Mobileum',
        },
        {
          color: '#ffcc00',
          value:
            'Still in requirements finalisation- though Security have NO development, Security role is to oversee and assist Cloud and Automation teams',
          displayValue:
            'Still In Requirements Finalisation- Though Security Have No Development, Security Role Is To Oversee And Assist Cloud And Automation Teams',
        },
        {
          color: '#50c878',
          value:
            'As new requirement, Dev team is working to build user friendly template.\r\n20210827 : Sponsor decided exception use case to be out of scope',
          displayValue:
            'As New Requirement, Dev Team Is Working To Build User Friendly Template.\r\n20210827 : Sponsor Decided Exception Use Case To Be Out Of Scope',
        },
        {
          color: '#c6e1e8',
          value:
            'Not a Security project, but managed by Security PMD resource with an NDA.',
          displayValue:
            'Not A Security Project, But Managed By Security Pmd Resource With An Nda.',
        },
        {
          color: '#d1d1e0',
          value: 'Closed, No further action required.',
          displayValue: 'Closed, No Further Action Required.',
        },
        {
          color: '#a48a9e',
          value:
            'This is a priority project from Device team, they are requesting our assistance. Approved by Sharad.',
          displayValue:
            'This Is A Priority Project From Device Team, They Are Requesting Our Assistance. Approved By Sharad.',
        },
        {
          color: '#ea9e70',
          value: 'Priority from Mickey',
          displayValue: 'Priority From Mickey',
        },
        {
          color: '#ce7d78',
          value:
            'Project end date might change based on further scope addition after L3',
          displayValue:
            'Project End Date Might Change Based On Further Scope Addition After L3',
        },
        {
          color: '#63b598',
          value:
            'Minuku PO has been informed. They asking RoS PM to take it over .',
          displayValue:
            'Minuku Po Has Been Informed. They Asking Ros Pm To Take It Over .',
        },
        {
          color: '#64820f',
          value:
            "Finish: Dec 2021 (Only for Phase 1, we need to re-initiate timeline to meet Core's request i.e. by the end of Sep)",
          displayValue:
            "Finish: Dec 2021 (only For Phase 1, We Need To Re-initiate Timeline To Meet Core's Request I.e. By The End Of Sep)",
        },
        {
          color: '#6b2e5f',
          value:
            'QAE team has been updated. Handover document has been shared.  Team agreed to have a complete handover by 28th July 2021',
          displayValue:
            'Qae Team Has Been Updated. Handover Document Has Been Shared.  Team Agreed To Have A Complete Handover By 28th July 2021',
        },
        {
          color: '#1bb699',
          value:
            'QAE team has been updated. Handover document has been shared.  Team agreed to have a complete handover by 28th July 2022',
          displayValue:
            'Qae Team Has Been Updated. Handover Document Has Been Shared.  Team Agreed To Have A Complete Handover By 28th July 2022',
        },
        {
          color: '#fa06ec',
          value:
            'QAE team has been updated. Handover document has been shared.  Team agreed to have a complete handover by 28th July 2023',
          displayValue:
            'Qae Team Has Been Updated. Handover Document Has Been Shared.  Team Agreed To Have A Complete Handover By 28th July 2023',
        },
        {
          color: '#b2be57',
          value:
            'We have reduced the scope of this project by discussing with the stake holders.',
          displayValue:
            'We Have Reduced The Scope Of This Project By Discussing With The Stake Holders.',
        },
        {
          color: '#e33e52',
          value: 'Not completed yet, BSS issues need to be resolved.',
          displayValue: 'Not Completed Yet, Bss Issues Need To Be Resolved.',
        },
        {
          color: '#d6dd92',
          value:
            'Required to meet the MIC requirement to have a consumer NBIoT product.',
          displayValue:
            'Required To Meet The Mic Requirement To Have A Consumer Nbiot Product.',
        },
      ],
    },
    sequenceNumber: 20,
    columnType: 'status',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.578Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.578Z',
    modifiedOn: '2021-09-05T11:19:44.578Z',
    createdBy: null,
    modifiedBy: null,
    id: '18ea4873-3dcc-4bfa-f6c3-2de349836efb',
    name: 'Oasis',
    description: null,
    level: 0,
    metaData: {},
    sequenceNumber: 21,
    columnType: 'text',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.578Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.578Z',
    modifiedOn: '2021-09-05T11:19:44.578Z',
    createdBy: null,
    modifiedBy: null,
    id: '80ad90fa-5ae8-4faa-f9ed-d7ddb9c5f17b',
    name: 'Project home',
    description: null,
    level: 0,
    metaData: {},
    sequenceNumber: 22,
    columnType: 'text',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.578Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.578Z',
    modifiedOn: '2021-09-05T11:19:44.578Z',
    createdBy: null,
    modifiedBy: null,
    id: '5d2a128b-b3a3-e201-3d1f-48755f764212',
    name: 'Last Update By',
    description: null,
    level: 0,
    metaData: {},
    sequenceNumber: 23,
    columnType: 'text',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-16T12:18:49.413Z',
    deletedBy: null,
    createdOn: '2021-09-16T12:18:49.412Z',
    modifiedOn: '2021-09-16T12:18:49.412Z',
    createdBy: '855a04ac-3f28-ebd0-9ea7-4816b0818f2e',
    modifiedBy: '855a04ac-3f28-ebd0-9ea7-4816b0818f2e',
    id: '68d96948-dd97-1222-f0c4-b3897405622a',
    name: 'Last Updated',
    description: null,
    level: 0,
    metaData: {
      options: [],
      displayMode: 'both',
    },
    sequenceNumber: 24,
    columnType: 'lastUpdated',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-16T13:45:45.534Z',
    deletedBy: null,
    createdOn: '2021-09-16T13:45:45.533Z',
    modifiedOn: '2021-09-16T13:45:45.533Z',
    createdBy: '855a04ac-3f28-ebd0-9ea7-4816b0818f2e',
    modifiedBy: '855a04ac-3f28-ebd0-9ea7-4816b0818f2e',
    id: '3695052f-dcbc-26f7-f6f9-2d979b5fe08c',
    name: 'People',
    description: null,
    level: 0,
    metaData: {
      maxAllowed: 0,
    },
    sequenceNumber: 25,
    columnType: 'people',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-20T12:25:13.815Z',
    deletedBy: null,
    createdOn: '2021-09-20T12:25:13.814Z',
    modifiedOn: '2021-09-20T12:25:13.814Z',
    createdBy: '855a04ac-3f28-ebd0-9ea7-4816b0818f2e',
    modifiedBy: '855a04ac-3f28-ebd0-9ea7-4816b0818f2e',
    id: '869ee199-dcca-8d47-e359-da3ff12ef862',
    name: 'Priority',
    description: null,
    level: 0,
    metaData: {
      availablePriorities: [
        {
          color: '#DF0101',
          value: 'critical',
          bgColor: '#FFF0F0',
          displayValue: 'Critical',
        },
        {
          color: '#7D6E00',
          value: 'high',
          bgColor: '#FFF4D2',
          displayValue: 'High',
        },
        {
          color: '#DB8600',
          value: 'medium',
          bgColor: '#FFEFD6',
          displayValue: 'Medium',
        },
        {
          color: '#006497',
          value: 'low',
          bgColor: '#EBF7FE',
          displayValue: 'Low',
        },
      ],
    },
    sequenceNumber: 26,
    columnType: 'priority',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-24T09:33:08.040Z',
    deletedBy: null,
    createdOn: '2021-09-24T09:33:08.040Z',
    modifiedOn: '2021-09-24T09:33:08.040Z',
    createdBy: '855a04ac-3f28-ebd0-9ea7-4816b0818f2e',
    modifiedBy: '855a04ac-3f28-ebd0-9ea7-4816b0818f2e',
    id: 'f30a469f-7f85-4149-91a6-b2221f2bf976',
    name: 'Numbers',
    description: null,
    level: 0,
    metaData: {
      function: 'sum',
      fractionDigits: 2,
    },
    sequenceNumber: 27,
    columnType: 'number',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
  {
    deleted: false,
    deletedOn: '2021-09-24T10:14:44.661Z',
    deletedBy: null,
    createdOn: '2021-09-24T10:14:44.660Z',
    modifiedOn: '2021-09-24T10:14:44.660Z',
    createdBy: '855a04ac-3f28-ebd0-9ea7-4816b0818f2e',
    modifiedBy: '855a04ac-3f28-ebd0-9ea7-4816b0818f2e',
    id: '1dbb8a1b-4d6a-a791-5d64-ca2cec09aad2',
    name: 'Numbers 1',
    description: null,
    level: 0,
    metaData: {
      function: 'sum',
      fractionDigits: 2,
    },
    sequenceNumber: 28,
    columnType: 'number',
    format: {},
    workspaceColumnId: null,
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupId: null,
  },
];

export const sampleGroups: any = [
  {
    deleted: false,
    deletedOn: '2021-09-05T11:19:44.590Z',
    deletedBy: null,
    createdOn: '2021-09-05T11:19:44.577Z',
    modifiedOn: '2021-09-24T10:51:00.413Z',
    createdBy: '855a04ac-3f28-ebd0-9ea7-4816b0818f2e',
    modifiedBy: '855a04ac-3f28-ebd0-9ea7-4816b0818f2e',
    id: 'bc2f6b38-ed7c-1d21-56ce-5ccfddd0c9e4',
    name: 'Group',
    description: null,
    archived: false,
    color: '#008CFF',
    sequenceNumber: 1,
    metaData: {},
    boardId: 'af7b3fd2-96d1-630d-b283-942604be4b15',
    groupType: 'default',
  },
];

export const columnTypes: any = [
  { name: 'checkbox', description: '', metaData: { symbol: 'checkbox' } },
  {
    name: 'currency',
    description: '',
    metaData: { value: 0, unit: '$', function: 'sum' },
  },
  {
    name: 'date',
    description: '',
    metaData: { dayOfWeek: false, currentYear: false, format: 'yyyy-MM-dd' },
  },
  {
    name: 'datetime',
    description: '',
    metaData: {
      dayOfWeek: false,
      currentYear: false,
      format: 'yyyy-MM-dd hh:mm:ss',
    },
  },
  { name: 'dependency', description: '', metaData: {} },
  { name: 'dropdown', description: '', metaData: {} },
  { name: 'formula', description: '', metaData: { formula: '', columns: [] } },
  {
    name: 'number',
    description: '',
    metaData: { fractionDigits: 2, function: 'sum' },
  },
  { name: 'people', description: '', metaData: { maxAllowed: 0 } },
  { name: 'percentage', description: '', metaData: {} },
  {
    name: 'priority',
    description: '',
    metaData: {
      availablePriorities: [
        {
          value: 'critical',
          displayValue: 'Critical',
          color: '#DF0101',
          bgColor: '#FFF0F0',
        },
        {
          value: 'high',
          displayValue: 'High',
          color: '#7D6E00',
          bgColor: '#FFF4D2',
        },
        {
          value: 'medium',
          displayValue: 'Medium',
          color: '#DB8600',
          bgColor: '#FFEFD6',
        },
        {
          value: 'low',
          displayValue: 'Low',
          color: '#006497',
          bgColor: '#EBF7FE',
        },
      ],
    },
  },
  {
    name: 'status',
    description: '',
    metaData: {
      doneMarkColor: 'green',
      availableStatus: [
        { value: 'todo', displayValue: 'To Do', color: '#9C9C9C' },
        { value: 'in progress', displayValue: 'In Progress', color: '#F59600' },
        { value: 'stuck', displayValue: 'Stuck', color: '#DF0101' },
        { value: 'done', displayValue: 'Done', color: '#047205' },
      ],
    },
  },
  { name: 'tag', description: '', metaData: {} },
  { name: 'text', description: '', metaData: {} },
  { name: 'timeline', description: '', metaData: {} },
];
